name: Build Dependencies
on:
  push:
    branches:
      - master
jobs:
  Build-Dependecies-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      run: mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)